# Generated by Django 5.0.2 on 2024-06-23 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_idno', models.CharField(max_length=10)),
                ('Category_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Merchantgtsdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GST', models.CharField(blank=True, max_length=100)),
                ('MerchantName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=25)),
                ('product_id', models.IntegerField()),
                ('review_text', models.TextField()),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubCategory_idno', models.CharField(max_length=10)),
                ('SubCategory_title', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Merchant.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=25)),
                ('MerchantName', models.CharField(default='Merchant', max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('product_rating', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('product_image', models.ImageField(upload_to='products/')),
                ('currency', models.CharField(blank=True, choices=[('₹', 'INR'), ('$', 'USD'), ('€', 'EUR')], default='INR', max_length=3)),
                ('product_price', models.IntegerField()),
                ('product_discount_price', models.IntegerField(blank=True, default=0, null=True)),
                ('product_discount_percent', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('product_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('in_stock', models.BooleanField(default=False)),
                ('free_delivery', models.BooleanField(default=False)),
                ('return_delivery', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Merchant.category')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Merchant.subcategory')),
            ],
        ),
    ]
