# Generated by Django 5.0.6 on 2024-06-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchant', '0004_product_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(blank=True, choices=[('₹', 'INR'), ('$', 'USD'), ('€', 'EUR')], default='₹', max_length=3),
        ),
    ]
