# Generated by Django 5.0.7 on 2024-08-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchant', '0006_alter_product_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(blank=True, choices=[('₹', 'INR'), ('$', 'USD'), ('€', 'EUR')], default='₹', max_length=3),
        ),
    ]
