# Generated by Django 5.0.7 on 2024-08-09 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Merchant', '0008_alter_product_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='currency',
        ),
    ]
